// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gifvvpopdtpzymgibhkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZnZ2cG9wZHRwenltZ2liaGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Mjc4MzUsImV4cCI6MjA2NjUwMzgzNX0.2iDLib4l5d6GmesOounorDhVXqFuszcHK9awftSxyZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);